#!/usr/bin/env python
# Generated by jaraco.develop (https://bitbucket.org/jaraco/jaraco.develop)
import setuptools

setup_params = dict(
	name='jaraco.persona',
	use_hg_version=True,
	author="Jason R. Coombs",
	author_email="jaraco@jaraco.com",
	description="A CherryPy implementation of Persona auth",
	url="https://bitbucket.org/jaraco/jaraco.persona",
	packages=setuptools.find_packages(),
	namespace_packages=['jaraco'],
	zip_safe=False,
	install_requires=[
		'requests',
		'CherryPy',
	],
	setup_requires=[
		'hgtools',
	],
)
if __name__ == '__main__':
	setuptools.setup(**setup_params)
